// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYs1wBOpfTshrjh6NAjmaI6VW3yEW2Sk',
    appId: '1:577390499046:web:6085c5ea07e8f9b960d727',
    messagingSenderId: '577390499046',
    projectId: 'instaclone-494fa',
    authDomain: 'instaclone-494fa.firebaseapp.com',
    storageBucket: 'instaclone-494fa.firebasestorage.app',
    measurementId: 'G-L1C3J74XNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SD2JQYWHD2p1pqTbOBokVNNmEUA6XWI',
    appId: '1:577390499046:android:c064ee39fbb6e82b60d727',
    messagingSenderId: '577390499046',
    projectId: 'instaclone-494fa',
    storageBucket: 'instaclone-494fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymcY4KjFvQox1dxhPRwgqb_ZLt3BvRY4',
    appId: '1:577390499046:ios:f1387060e42208b260d727',
    messagingSenderId: '577390499046',
    projectId: 'instaclone-494fa',
    storageBucket: 'instaclone-494fa.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBymcY4KjFvQox1dxhPRwgqb_ZLt3BvRY4',
    appId: '1:577390499046:ios:f1387060e42208b260d727',
    messagingSenderId: '577390499046',
    projectId: 'instaclone-494fa',
    storageBucket: 'instaclone-494fa.firebasestorage.app',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhYs1wBOpfTshrjh6NAjmaI6VW3yEW2Sk',
    appId: '1:577390499046:web:4db273f10d5af4d760d727',
    messagingSenderId: '577390499046',
    projectId: 'instaclone-494fa',
    authDomain: 'instaclone-494fa.firebaseapp.com',
    storageBucket: 'instaclone-494fa.firebasestorage.app',
    measurementId: 'G-GLKJQNFF1K',
  );
}
